### ISSUE TITLE
Tacos need a description

### ISSUE THREAD

**Issue by abell95** [ctsstc/tacobout#35]
Allow shop admins to add blurbs to their tacos (140 char max)

**Comment by ctsstc** [comment]
## Acceptance
- Migration: add description
- Add model validator

I do not think we need to set the constraint in the db, but we could if we want to (I think)

**Comment by abell95** [comment]
Tacos actually always had descriptions

Press F to respect

**Comment by ctsstc** [comment]
F
> Pays respects
